Ext.define('erp.model.Financeiro.BaixaContaPagar.ContaPagarModel', {
    extend: 'Ext.data.Model',
    fields: [
      {name: 'CD_CONTA_PAGAR', type: 'int', useNull: true},
	  {name: 'DS_CONTA_PAGAR', type: 'string', useNull: true},	  
	  {name: 'CD_EMPRESA', type: 'int', useNull: true},
	  {name: 'CD_PESSOA', type: 'int', useNull: true},
	  {name: 'NM_PESSOA', type: 'string', useNull: true},
	  {name: 'CD_PESSOA_PJ', type: 'int', useNull: true},
	  {name: 'NM_FANTASIA', type: 'string', useNull: true},
	  {name: 'NM_RAZAO_SOCIAL', type: 'string', useNull: true},
	  {name: 'DT_CADASTRO', type: 'date', dateFormat: 'Y-m-d H:i:s', useNull: true},
	  {name: 'DT_ALTERACAO', type: 'date', dateFormat: 'Y-m-d H:i:s', useNull: true},
	  {name: 'DT_PREVISAO_CONTA', type: 'date', dateFormat: 'Y-m-d', useNull: true},
	  {name: 'CD_USUARIO_CADASTRO', type: 'int', useNull: true},
	  {name: 'DS_USUARIO_CADASTRO', type: 'string', useNull: true},
	  {name: 'CD_USUARIO_ALTERACAO', type: 'int', useNull: true},
	  {name: 'DS_USUARIO_ALTERACAO', type: 'string', useNull: true},
	  {name: 'DT_LIQUIDACAO', type: 'date', dateFormat: 'Y-m-d', useNull: true},
	  {name: 'VL_CONTA', type: 'float', useNull: true},
	  {name: 'DT_VENCIMENTO', type: 'date', dateFormat: 'Y-m-d', useNull: true},
	  {name: 'VL_MORA_JURO', type: 'float', useNull: true},
	  {name: 'VL_DESPESA', type: 'float', useNull: true},
	  {name: 'VL_DESCONTO', type: 'float', useNull: true},
	  {name: 'VL_LIQUIDACAO', type: 'float', useNull: true},
	  {name: 'CD_PLANO_CONTA', type: 'int', useNull: true},
	  {name: 'DS_PLANO_CONTA', type: 'string', useNull: true},
	  {name: 'CD_CONTA', type: 'string', useNull: true},
	  {name: 'CD_PARCELA', type: 'string', useNull: true},
	  {name: 'DS_OBSERVACAO', type: 'string', useNull: true},
	  {name: 'CD_SITUACAO', type: 'string', useNull: true},
	  {name: 'DS_SITUACAO', type: 'string', useNull: true}
	  ], 
	idProperty: 'CD_CONTA_PAGAR'
});